# Application server stack - Kris 22
# 
# Create networks before running docker-compose -p application_server up -d

# .env file variables:
# $PUID
# $PGID
# $TZ  
# $DOCKERDIR

version: "3.7"

# Applications
# [9000] NGINX proxy manager
# [9001] Portainer

services:
  # NGINX proxy manager: Reverse proxy
  #
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: always
    ports:
      - '80:80'   # Public HTTP
      - '443:443' # Public HTTPS
      - '9000:81' # Admin console
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    environment:
      DB_SQLITE_FILE: '/data/database.sqlite'
    volumes:
      - ${DOCKERDIR}/app_data/npm:/data
      - ${DOCKERDIR}/app_data/npm/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro

  # Portainer: Docker management
  #
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9001:9000"
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/app_data/portainer:/data
      - /etc/localtime:/etc/localtime:ro